class Symbols
  attr_reader :string
  def initialize(string)
    @string = string.to_s
  end

  def symbols
    #binding.pry
    @string.reverse!
    @string.downcase!
    @string.gsub!("a","~")
    @string.gsub!("b","!")
    @string.gsub!("c","@")
    @string.gsub!("d","#")
    @string.gsub!("e","$")
    @string.gsub!("f","%")
    @string.gsub!("g","^")
    @string.gsub!("h","&")
    @string.gsub!("i","*")
    @string.gsub!("j","(")
    @string.gsub!("k",")")
    @string.gsub!("l","-")
    @string.gsub!("m","_")
    @string.gsub!("n","=")
    @string.gsub!("o","+")
    @string.gsub!("p","[")
    @string.gsub!("q","]")
    @string.gsub!("r","{")
    @string.gsub!("s","}")
    @string.gsub!("t","∆")
    @string.gsub!("u","œ")
    @string.gsub!("v","®")
    @string.gsub!("w",";")
    @string.gsub!("x",",")
    @string.gsub!("y","<")
    @string.gsub!("z",".")
    @string.gsub!("1",">")
    @string.gsub!("2","?")
    @string.gsub!("3","/")
    @string.gsub!("4","`")
    @string.gsub!("5","ø")
    @string.gsub!("6","˚")
    @string.gsub!("7","¬")
    @string.gsub!("8","å")
    @string.gsub!("9","µ")
    @string.gsub!("0","¥")
  end

  def symbols2
    @string.gsub!("a", "©")
    @string.gsub!("b", "ø")
    @string.gsub!("c","µ")
    @string.gsub!("d","æ")
    @string.gsub!("e","π")
    @string.gsub!("f","¬")
    @string.gsub!("g","å")
    @string.gsub!("h","≈")
    @string.gsub!("i","~")
    @string.gsub!("j","¢")
    @string.gsub!("k","•")
    @string.gsub!("l","º")
    @string.gsub!("m","ª")
    @string.gsub!("n","¥")
    @string.gsub!("o","Ω")
    @string.gsub!("p","'")
    @string.gsub!("q","]")
    @string.gsub!("r","|")
    @string.gsub!("s","∆")
    @string.gsub!("t","˚")
    @string.gsub!("u","ß")
    @string.gsub!("v","∞")
    @string.gsub!("w","§")
    @string.gsub!("x","£")
    @string.gsub!("y",".")
    @string.gsub!("z",">")
    @string.gsub!("1","?")
    @string.gsub!("2",";")
    @string.gsub!("3",":")
    @string.gsub!("4",",")
    @string.gsub!("5","√")
    @string.gsub!("6","≥")
    @string.gsub!("7","÷")
    @string.gsub!("8","…")
    @string.gsub!("9","»")
    @string.gsub!("0","«")
  end

  def symbols3
    @string.gsub!("a","∆")
    @string.gsub!("b","¬")
    @string.gsub!("c","¥")
    @string.gsub!("d","º")
    @string.gsub!("e","∞")
    @string.gsub!("f","ˆ")
    @string.gsub!("g","π")
    @string.gsub!("h","∑")
    @string.gsub!("i","®")
    @string.gsub!("j","˜")
    @string.gsub!("k","~")
    @string.gsub!("l","©")
    @string.gsub!("m","æ")
    @string.gsub!("n","≤")
    @string.gsub!("o","÷")
    @string.gsub!("p","≥")
    @string.gsub!("q","…")
    @string.gsub!("r","‘")
    @string.gsub!("s","“")
    @string.gsub!("t","«")
    @string.gsub!("u","»")
    @string.gsub!("v","¶")
    @string.gsub!("w","§")
    @string.gsub!("x","™")
    @string.gsub!("y","£")
    @string.gsub!("z","–")
    @string.gsub!("1","≠")
    @string.gsub!("2","±")
    @string.gsub!("3","Â")
    @string.gsub!("4","◊")
    @string.gsub!("5","Ç")
    @string.gsub!("6","Á")
    @string.gsub!("7","Ø")
    @string.gsub!("8","¸")
    @string.gsub!("9","˘")
    @string.gsub!("0","¿")
  end

  def symbols4
    @string.gsub!("a","Î")
    @string.gsub!("b","˝")
    @string.gsub!("c","")
    @string.gsub!("d","˜")
    @string.gsub!("e","Â")
    @string.gsub!("f","µ")
    @string.gsub!("g","¬")
    @string.gsub!("h","≈")
    @string.gsub!("i","ø")
    @string.gsub!("j","∏")
    @string.gsub!("k","◊")
    @string.gsub!("l","ç")
    @string.gsub!("m","Ω")
    @string.gsub!("n","¸")
    @string.gsub!("o","©")
    @string.gsub!("p","†")
    @string.gsub!("q","∞")
    @string.gsub!("r","ﬁ")
    @string.gsub!("s","ﬂ")
    @string.gsub!("t","‡")
    @string.gsub!("u","°")
    @string.gsub!("v","–")
    @string.gsub!("w","ª")
    @string.gsub!("x","‹")
    @string.gsub!("y","›")
    @string.gsub!("z","Œ")
    @string.gsub!("1","ˇ")
    @string.gsub!("2","Ó")
    @string.gsub!("3","„")
    @string.gsub!("4","‘")
    @string.gsub!("5","’")
    @string.gsub!("6","¿")
    @string.gsub!("7","÷")
    @string.gsub!("8","˘")
    @string.gsub!("9","¯")
    @string.gsub!("0","Ú")
  end
  
  def determine
   
    if @string.length < 5 && @string.length > 0
      symbols
      #binding.pry
    elsif @string.length < 10 && @string.length > 6
      symbols2
    elsif @string.length < 31 && @string.length > 25
      symbols3
    else
      symbols4
    end
  end

end
